# -*- coding: utf-8 -*-
"""security breach link

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VAcog_CutaaDNE1mC6IElqPwHq0tX1ut
"""

import requests
import feedparser
import re
from datetime import datetime, timezone
from transformers import pipeline

# 1. 원본 RSS URL과 AllOrigins 프록시 URL
rss_url   = 'https://databreaches.net/feed/'
proxy_url = 'https://api.allorigins.win/raw?url=' + rss_url

# 2. 오늘 날짜 (UTC 기준)
today = datetime.now(timezone.utc).date()

# 3. Hugging Face 요약 파이프라인 로딩
summarizer = pipeline(
    "summarization",
    model="facebook/bart-large-cnn",
    device=0  # GPU가 없으면 제거하세요
)

# 4. AllOrigins 통해 RSS 가져오기
try:
    resp = requests.get(proxy_url, headers={'User-Agent': 'Mozilla/5.0'}, timeout=10)
    resp.raise_for_status()
    feed = feedparser.parse(resp.text)
except Exception as e:
    print("❌ RSS fetch error:", e)
    feed = None

# 5. 오늘자 기사 수집 및 제목·링크·요약 저장
articles = []
if feed:
    for entry in feed.entries:
        if 'published_parsed' in entry:
            pub_date = datetime(*entry.published_parsed[:6], tzinfo=timezone.utc).date()
            if pub_date == today:
                # HTML 태그 제거한 원문 요약 텍스트
                raw_summary = entry.get('summary', '')
                clean_summary = re.sub(r'<[^>]+>', '', raw_summary)
                # AI 요약 생성
                try:
                    ai_sum = summarizer(
                        clean_summary,
                        max_length=60,
                        min_length=15,
                        do_sample=False
                    )[0]['summary_text'].strip()
                except Exception:
                    ai_sum = "(AI summary unavailable)"
                articles.append({
                    'title': entry.title,
                    'link': entry.link,
                    'ai_summary': ai_sum
                })

# 6. 결과 출력
count = len(articles)
print(f"📅 Data from DataBreaches.net - What Happened today ({today}) in Cyber?: Today, we have {count} data breaches\n")

if articles:
    for i, art in enumerate(articles, 1):
        print(f"{i}. {art['title']}")
        print(f"   🔗 {art['link']}")
        print(f"   🧐 AI Summary: {art['ai_summary']}\n")
else:
    print("❌ 오늘 날짜의 뉴스 기사가 없습니다.")